
INSERT INTO country (name) VALUES
('Afghanistan'),
('Africa'),
('Africa (FAO)'),
('Algeria'),
('Americas (FAO)'),
('Argentina'),
('Asia'),
('Asia (FAO)'),
('Australia'),
('Azerbaijan'),
('Bosnia and Herzegovina'),
('Bulgaria'),
('Burkina Faso'),
('Central America (FAO)'),
('Central Asia (FAO)'),
('Chile'),
('China'),
('China (FAO)'),
('Cote d''Ivoire'),
('Croatia'),
('Cyprus'),
('Eastern Asia (FAO)'),
('Eastern Europe (FAO)'),
('Eswatini'),
('Europe'),
('Europe (FAO)'),
('European Union (27)'),
('European Union (27) (FAO)'),
('France'),
('Georgia'),
('Greece'),
('High-income countries'),
('Hungary'),
('Iran'),
('Iraq'),
('Israel'),
('Italy'),
('Jordan'),
('Kazakhstan'),
('Kyrgyzstan'),
('Land Locked Developing Countries (FAO)'),
('Least Developed Countries (FAO)'),
('Lebanon'),
('Libya'),
('Low Income Food Deficit Countries (FAO)'),
('Low-income countries'),
('Lower-middle-income countries'),
('Mexico'),
('Moldova'),
('Morocco'),
('Nepal'),
('Net Food Importing Developing Countries (FAO)'),
('North America'),
('North Macedonia'),
('Northern Africa (FAO)'),
('Northern America (FAO)'),
('Oceania'),
('Oceania (FAO)'),
('Pakistan'),
('Palestine'),
('Portugal'),
('Saudi Arabia'),
('Slovenia'),
('South America'),
('South America (FAO)'),
('Southern Africa (FAO)'),
('Southern Asia (FAO)'),
('Southern Europe (FAO)'),
('Spain'),
('Syria'),
('Tajikistan'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('USSR'),
('Ukraine'),
('United Arab Emirates'),
('United States'),
('Upper-middle-income countries'),
('Uzbekistan'),
('Western Africa (FAO)'),
('Western Asia (FAO)'),
('Western Europe (FAO)'),
('World'),
('Yemen'),
('Yugoslavia'),
('Albania'),
('Armenia'),
('Austria'),
('Belarus'),
('Belgium'),
('Belgium-Luxembourg (FAO)'),
('Bhutan'),
('Bolivia'),
('Brazil'),
('Canada'),
('Caribbean (FAO)'),
('Colombia'),
('Czechia'),
('Czechoslovakia'),
('Denmark'),
('Eastern Africa (FAO)'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Estonia'),
('Finland'),
('Germany'),
('Grenada'),
('Guatemala'),
('Honduras'),
('India'),
('Ireland'),
('Japan'),
('Kenya'),
('Latvia'),
('Lithuania'),
('Luxembourg'),
('Madagascar'),
('Malawi'),
('Malta'),
('Montenegro'),
('Netherlands'),
('New Zealand'),
('North Korea'),
('Northern Europe (FAO)'),
('Norway'),
('Paraguay'),
('Peru'),
('Poland'),
('Reunion'),
('Romania'),
('Russia'),
('Saint Vincent and the Grenadines'),
('Serbia'),
('Serbia and Montenegro'),
('Slovakia'),
('Small Island Developing States (FAO)'),
('South Africa'),
('South Korea'),
('Sweden'),
('Switzerland'),
('Taiwan'),
('United Kingdom'),
('Uruguay'),
('Zimbabwe'),
('Cameroon'),
('Middle Africa (FAO)'),
('Bangladesh'),
('Indonesia'),
('Malaysia'),
('Maldives'),
('Myanmar'),
('South-eastern Asia (FAO)'),
('Sri Lanka'),
('Thailand'),
('Costa Rica'),
('Philippines'),
('Angola'),
('Bahamas'),
('Barbados'),
('Central African Republic'),
('Congo'),
('Cook Islands'),
('Cuba'),
('Democratic Republic of Congo'),
('Dominica'),
('Dominican Republic'),
('East Timor'),
('Ethiopia'),
('Fiji'),
('French Guiana'),
('French Polynesia'),
('Ghana'),
('Guadeloupe'),
('Guyana'),
('Haiti'),
('Jamaica'),
('Martinique'),
('Melanesia'),
('Panama'),
('Polynesia'),
('Puerto Rico'),
('Rwanda'),
('Saint Lucia'),
('Samoa'),
('Seychelles'),
('Suriname'),
('Trinidad and Tobago'),
('Venezuela'),
('Vietnam'),
('Mali'),
('Niger'),
('Togo'),
('Zambia'),
('Antigua and Barbuda'),
('Bahrain'),
('Belize'),
('Benin'),
('Brunei'),
('Burundi'),
('Cambodia'),
('Cape Verde'),
('Comoros'),
('Equatorial Guinea'),
('Ethiopia (former)'),
('Gabon'),
('Guinea'),
('Guinea-Bissau'),
('Kiribati'),
('Laos'),
('Liberia'),
('Mauritius'),
('Micronesia (FAO)'),
('Micronesia (country)'),
('Mozambique'),
('New Caledonia'),
('Nicaragua'),
('Nigeria'),
('Niue'),
('Oman'),
('Papua New Guinea'),
('Sao Tome and Principe'),
('Senegal'),
('Singapore'),
('Solomon Islands'),
('Somalia'),
('Sudan'),
('Sudan (former)'),
('Tanzania'),
('Tokelau'),
('Tonga'),
('Tuvalu'),
('Uganda'),
('Vanuatu'),
('Eritrea'),
('Iceland'),
('Kuwait'),
('Lesotho'),
('Mauritania'),
('Mongolia'),
('Qatar'),
('Chad'),
('Djibouti'),
('Namibia'),
('South Sudan'),
('Hong Kong'),
('Nauru'),
('Sierra Leone'),
('Botswana'),
('Saint Kitts and Nevis'),
('Gambia'),
('Marshall Islands'),
('Macao'),
('Faroe Islands');

INSERT INTO year (value) VALUES
(1976),
(1977),
(1978),
(1979),
(1980),
(1981),
(1982),
(1983),
(1984),
(1985),
(1986),
(1987),
(1988),
(1989),
(1990),
(1991),
(1992),
(1993),
(1994),
(1995),
(1996),
(1997),
(1998),
(1999),
(2000),
(2001),
(2002),
(2003),
(2004),
(2005),
(2006),
(2007),
(2008),
(2009),
(2010),
(2011),
(2012),
(2013),
(2014),
(2015),
(2016),
(2017),
(2018),
(2019),
(2020),
(2021),
(2022),
(1961),
(1962),
(1963),
(1964),
(1965),
(1966),
(1967),
(1968),
(1969),
(1970),
(1971),
(1972),
(1973),
(1974),
(1975),
(1275),
(1305),
(1355),
(1405),
(1455),
(1555),
(1605),
(1655),
(1705),
(1755),
(1805),
(1855),
(1865),
(1887),
(1912),
(1932),
(1944),
(1866),
(1867),
(1868),
(1869),
(1870),
(1871),
(1872),
(1873),
(1874),
(1875),
(1876),
(1877),
(1878),
(1879),
(1880),
(1881),
(1882),
(1883),
(1884),
(1885),
(1886),
(1888),
(1889),
(1890),
(1891),
(1892),
(1893),
(1894),
(1895),
(1896),
(1897),
(1898),
(1899),
(1900),
(1901),
(1902),
(1903),
(1904),
(1905),
(1906),
(1907),
(1908),
(1909),
(1910),
(1911),
(1913),
(1914),
(1915),
(1916),
(1917),
(1918),
(1919),
(1920),
(1921),
(1922),
(1923),
(1924),
(1925),
(1926),
(1927),
(1928),
(1929),
(1930),
(1931),
(1933),
(1934),
(1935),
(1936),
(1937),
(1938),
(1939),
(1940),
(1941),
(1942),
(1943),
(1945),
(1946),
(1947),
(1948),
(1949),
(1950),
(1951),
(1952),
(1953),
(1954),
(1955),
(1956),
(1957),
(1958),
(1959),
(1960),
(2023),
(1850);

INSERT INTO crop (name) VALUES
('almond'),
('apples'),
('apricots'),
('areca_nuts'),
('artichokes'),
('asparagus'),
('avocados'),
('bambara_beans__dry'),
('banana'),
('barley'),
('bean'),
('beans__green'),
('blueberries'),
('broad_beans_and_horse_beans__green'),
('broad_beans'),
('buckwheat'),
('cabbages'),
('canary_seed'),
('carrots_and_turnips'),
('cashew_nuts'),
('cashewapple'),
('cassava_leaves'),
('cassava'),
('castor_oil_seed'),
('cauliflowers_and_broccoli'),
('cereal'),
('cherries'),
('chestnut'),
('chickpeas'),
('chicory_roots'),
('chillies_and_peppers__green__capsicum_spp__and_pimenta_spp'),
('chillies_and_peppers'),
('citrus_fruit'),
('cocoa'),
('coconuts'),
('coffee'),
('cow_peas'),
('cranberries'),
('cucumbers_and_gherkins'),
('currants'),
('dates'),
('eggplants'),
('fibre_crops__fibre_equivalent'),
('fibre_crops'),
('figs'),
('flax__raw_or_retted'),
('fonio'),
('fruit'),
('garlic'),
('gooseberries'),
('grapefruit'),
('grapes'),
('green_maize'),
('groundnut'),
('hazelnuts'),
('hempseed'),
('herbs__e_g__fennel'),
('hop_cones'),
('jojoba_seeds'),
('jute'),
('kapok_fruit'),
('karite_nuts'),
('kenaf__and_other_textile_bast_fibres__raw_or_retted'),
('kiwi'),
('kola_nuts'),
('leeks'),
('lemons_and_limes'),
('lentils'),
('lettuce'),
('linseed'),
('locust_beans__carobs'),
('lupins'),
('maize'),
('mangoes'),
('mate_leaves'),
('melon'),
('melonseed'),
('millet'),
('mixed_grains'),
('mustard_seed'),
('natural_rubber_in_primary_forms'),
('oats'),
('oilcrops__cake_equivalent'),
('oilcrops__oil_equivalent'),
('okra'),
('olives'),
('onions_and_shallots__green'),
('onions'),
('orange'),
('other_pome_fruits'),
('other_stone_fruits'),
('oilpalm'),
('papayas'),
('peaches_and_nectarines'),
('pears'),
('pea'),
('peas__green'),
('pepper'),
('peppermint__spearmint'),
('persimmons'),
('pigeon_peas'),
('pineapples'),
('pistachios'),
('plantains'),
('plums'),
('poppy_seeds'),
('potato'),
('pulses'),
('pumpkins__squash_and_gourds'),
('pyrethrum__dried_flowers'),
('quinces'),
('quinoa'),
('ramie__raw_or_retted'),
('rapeseed'),
('raspberries'),
('rice'),
('roots_and_tubers'),
('rye'),
('safflower_seed'),
('cotton'),
('sesame_seed'),
('sorghum'),
('sour_cherries'),
('soybean'),
('spinach'),
('strawberries'),
('string_beans'),
('sugarbeet'),
('sugarcane'),
('sugar_crops'),
('sunflower'),
('sweet_potatoes'),
('tallowtree_seeds'),
('tangerines'),
('taro'),
('tea'),
('tobacco'),
('tomato'),
('treenuts'),
('triticale'),
('true_hemp__raw_or_retted'),
('tung_nuts'),
('vegetables'),
('vetches'),
('walnuts'),
('watermelons'),
('wheat'),
('yams'),
('yautia');

INSERT INTO crop_yield (country_id, crop_id, year_id, value)
VALUES
((SELECT id FROM country WHERE name = 'Afghanistan'),
(SELECT id FROM crop WHERE name = 'almond'),
(SELECT id FROM year WHERE value = 1976),
1.661),
((SELECT id FROM country WHERE name = 'Afghanistan'),
(SELECT id FROM crop WHERE name = 'almond'),
(SELECT id FROM year WHERE value = 1977),
1.5),
((SELECT id FROM country WHERE name = 'Afghanistan'),
(SELECT id FROM crop WHERE name = 'almond'),
(SELECT id FROM year WHERE value = 1978),
2.0),
((SELECT id FROM country WHERE name = 'Afghanistan'),
(SELECT id FROM crop WHERE name = 'almond'),
(SELECT id FROM year WHERE value = 1979),
1.75),
((SELECT id FROM country WHERE name = 'Afghanistan'),
(SELECT id FROM crop WHERE name = 'almond'),
(SELECT id FROM year WHERE value = 1980),
1.7069),
((SELECT id FROM country WHERE name = 'Afghanistan'),
(SELECT id FROM crop WHERE name = 'almond'),
(SELECT id FROM year WHERE value = 1981),
1.3793),
((SELECT id FROM country WHERE name = 'Afghanistan'),
(SELECT id FROM crop WHERE name = 'almond'),
(SELECT id FROM year WHERE value = 1982),
1.8966),
((SELECT id FROM country WHERE name = 'Afghanistan'),
(SELECT id FROM crop WHERE name = 'almond'),
(SELECT id FROM year WHERE value = 1983),
1.7018),
((SELECT id FROM country WHERE name = 'Afghanistan'),
(SELECT id FROM crop WHERE name = 'almond'),
(SELECT id FROM year WHERE value = 1984),
1.8420999),
((SELECT id FROM country WHERE name = 'Afghanistan'),
(SELECT id FROM crop WHERE name = 'almond'),
(SELECT id FROM year WHERE value = 1985),
1.6071);
