# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  datavisapi:
    image: datavisapi
    restart: always
    build:
      context: .
      dockerfile: datavis-api/Dockerfile
    ports:
      - 5065:5065
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crop_yields_owid
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - ./database/postgres:/docker-entrypoint-initdb.d
    - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
